sudo: required  
dist: trusty 
language: node_js
node_js:
  - "7.9"

branches:
  only:
    - master

script:
  - npm run validate
  - npm run documentation
  - touch docs/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs
  on:
    branch: master

notifications:
  email:
    on_failure: change
    on_success: change
